accounts/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('',views.login_user,name="login_user"),
    path('logout/',views.logout_user,name="logout_user"),
    path('signup/',views.signup,name="signup"),
    path('link-user-to-employee/', views.link_user_to_employee, name="link_user_to_employee"),
]   

# # urlpatterns = [
# #     path('',views.employee_login,name="employee_login"),
# #     path('logout',views.employee_logout,name="employee_logout"),
# #     path('signup',views.signup,name="signup"),
# # ]   

employee/urls.py
# from django.urls import path
# from . import views

# # urlpatterns = [
# #     path('', views.home, name="home"),
# #     path('work', views.work, name="work"),
# #     path('request', views.request, name="request"),
# #     path('notice', views.notice, name="notice"),
# #     path('attendance', views.attendance, name="attendance"),
# # ]   
# urlpatterns = [
#     path('dashboard',views.dashboard,name="dashboard"),
#     path('attendance',views.attendance,name="attendance"),
#     path('notice',views.notice,name="notice"),
#     path('noticedetail/?P<id>/',views.noticedetail,name="noticedetail"),
#     path('assignwork',views.assignWork,name="assignwork"),
#     path('mywork',views.mywork,name="mywork"),
#     path('workdetails/?P<wid>/',views.workdetails,name="workdetails"),
#     path('editAW/', views.assignedworklist, name='assignedworklist'),
#     path('deletework/?P<wid>/',views.deletework,name="deletework"),
#     path('updatework/?P<wid>',views.updatework,name="updatework"),
#     path('make_request/', views.make_request, name='make_request'),
#     # path('makeRequest', views.makeRequest, name="makeRequest"),
#     # path('viewRequest',views.viewRequest,name="viewRequest"),
#     path('requestdetails/?P<rid>/',views.requestdetails,name="requestdetails"),
#     # path('makeRequest', views.makeRequest, name="makeRequest"),
#     # path('make_request/', views.make_request, name='make_request'),
#     path('admin/expenditure_requests/', views.admin_expenditure_requests, name='admin_expenditure_requests'),
#     path('admin/handle_expenditure_request/<int:pk>/', views.handle_expenditure_request, name='handle_expenditure_request'),
#     path('admin/handle_leave_request/<int:pk>/', views.handle_leave_request, name='handle_leave_request'),
#     path('admin/handle_other_request/<int:pk>/', views.handle_other_request, name='handle_other_request'),
#     # path('admin/requests', views.admin_requests, name="admin_requests"),
#     # path('admin/approve_request/<int:request_id>/<str:request_type>/', views.approve_request, name="approve_request"),
#     # path('admin/hold_request/<int:request_id>/<str:request_type>/', views.hold_request, name="hold_request"),
#     # path('admin/delete_request/<int:request_id>/<str:request_type>/', views.delete_request, name="delete_request"),
    
# ]

################################################################
# 23/12/24 above code is working
###############################################################3
from django.urls import path
from . import views
from .views import request_page
# from employee.views import make_request_view, check_request_status

# urlpatterns = [
#     path('', views.home, name="home"),
#     path('work', views.work, name="work"),
#     path('request', views.request, name="request"),
#     path('notice', views.notice, name="notice"),
#     path('attendance', views.attendance, name="attendance"),
# ]   
urlpatterns = [
    # path('',views.login_user,name="login_user"),
    # path('logout',views.logout_user,name="logout_user"),
    # path('signup',views.signup,name="signup"),
    path('dashboard',views.dashboard,name="dashboard"),
    path('attendance',views.attendance,name="attendance"),
    path('attendance-summary/', views.attendance_summary, name='attendance_summary'),
    # path('attendance', views.attendance_summary, name='attendance'),
    path('notice',views.notice,name="notice"),
    path('noticedetail/?P<id>/',views.noticedetail,name="noticedetail"),
    # path('assignwork',views.assignWork,name="assignwork"),
    # path('mywork',views.mywork,name="mywork"),
    # path('workdetails/?P<wid>/',views.workdetails,name="workdetails"),
    path('editAW/', views.assignedworklist, name='assignedworklist'),
    path('deletework/?P<wid>/',views.deletework,name="deletework"),
    # path('updatework/?P<wid>',views.updatework,name="updatework"),
    path('make_request/', views.make_request, name='make_request'),
    # path('makeRequest', views.makeRequest, name="makeRequest"),
    # path('viewRequest',views.viewRequest,name="viewRequest"),
    path('requestdetails/?P<rid>/',views.requestdetails,name="requestdetails"),
    # path('makeRequest', views.makeRequest, name="makeRequest"),
    # path('make_request/', views.make_request, name='make_request'),
    path('admin/expenditure_requests/', views.admin_expenditure_requests, name='admin_expenditure_requests'),
    path('admin/handle_expenditure_request/<int:pk>/', views.handle_expenditure_request, name='handle_expenditure_request'),
    path('admin/handle_leave_request/<int:pk>/', views.handle_leave_request, name='handle_leave_request'),
    path('admin/handle_other_request/<int:pk>/', views.handle_other_request, name='handle_other_request'),
    path('expenditure_requests/', views.make_expenditure_request, name='expenditure_requests'),
    path('user_notifications/',views.user_notifications,name="user_notifications"),
    path('assign_task/', views.assign_task, name='assign_task'),
    path('my_work/', views.my_work, name='my_work'),
    path('workdetails/<int:wid>/', views.work_details, name='workdetails'),  # New URL for work details
    path('mark_task_completed/<int:task_id>/', views.mark_task_completed, name='mark_task_completed'),  # New URL pattern
    path('requests/', request_page, name='request_page'),
    path('all-requests/', views.view_all_requests, name='view_all_requests'),  # New URL for viewing all requests
    # path('make-request/', make_request_view, name='make_request'),
    # path('check-request-status/', check_request_status, name='check_request_status'),


    # path('assignwork/', views.assignWork, name='assignwork'),
    # path('my_work/', views.my_work, name='my_work'),
    # path('admin/requests', views.admin_requests, name="admin_requests"),
    # path('admin/approve_request/<int:request_id>/<str:request_type>/', views.approve_request, name="approve_request"),
    # path('admin/hold_request/<int:request_id>/<str:request_type>/', views.hold_request, name="hold_request"),
    # path('admin/delete_request/<int:request_id>/<str:request_type>/', views.delete_request, name="delete_request"),
    
]

empmanagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from employee.admin import custom_admin_site
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', custom_admin_site.urls),
    path('', include('accounts.urls')),
    path('ems/', include('employee.urls')),
    # Add this to handle Django's built-in auth URLs
    path('accounts/login/', RedirectView.as_view(url='/')),  # Redirect to our custom login
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee/models.py
from pyexpat import model
from django.db import models
from pickle import TRUE
from turtle import title
from datetime import datetime
from django.contrib.auth.models import User  # Assuming Employee is related to Django's User model
# from .models import Employee  
designations_opt = (
    ('Team Leader','Team Leader'),
    ('Project Manager','Project Manager'),
    ('Senior Developer','Senior Developer'),
    ('Junior Developer','Junior Developer'),
    ('Intern','Intern'),
    ('QA Tester','QA Tester')
)

months = (
    ('January','January'),
    ('February','February'),
    ('March','March'),
    ('April','April'),
    ('May','May'),
    ('June','June'),
    ('July','July'),
    ('August','August'),
    ('September','September'),
    ('October','October'),
    ('November','November'),
    ('December','December')
)

days = (('0','0'),('1','1'),('2','2'),('3','3'),('4','4'),('5','5'),('6','6'),('7','7'),('8','8'),('9','9'),('10','10'),
('11','11'),('12','12'),('13','13'),('14','14'),('15','15'),('16','16'),('17','17'),('18','18'),('19','19'),('20','20'),
('21','21'),('22','22'),('23','23'),('24','24'),('25','25'),('26','26'),('27','27'),('28','28'),('29','29'),('30','30'),('31','31'))

# Create your models here.

class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # username = models.CharField(max_length=150, unique=True, null=True, blank=True)
    eID = models.CharField(primary_key=True,max_length=20)
    # username = models.CharField(max_length=50)
    firstName = models.CharField(max_length=50)
    middleName = models.CharField(max_length=50)
    lastName = models.CharField(max_length=50)
    phoneNo = models.CharField(max_length=12,unique=True)
    email = models.EmailField(max_length=70,unique=True)
    addharNo = models.CharField(max_length=20,unique=True)
    dOB = models.DateField()
    designation = models.CharField(max_length=50,choices=designations_opt)
    salary = models.CharField(max_length=20)
    joinDate = models.DateField()

    def __str__(self):  
        return "%s %s %s " % (self.eID, self.firstName, self.lastName)
    
from django.db import models
from datetime import timedelta

class Attendance(models.Model):
    eId = models.ForeignKey(Employee, on_delete=models.CASCADE)
    login_time = models.DateTimeField(null=True, blank=True)
    logout_time = models.DateTimeField(null=True, blank=True)
    login_location = models.CharField(max_length=255, null=True, blank=True)
    logout_location = models.CharField(max_length=255, null=True, blank=True)
    total_working_hours = models.DurationField(default=timedelta)
    date = models.DateField(auto_now_add=True)  # Add date field with auto_now_add
    status = models.CharField(max_length=20, default='Present')  # Add status field with default

    def calculate_hours(self):
        """Calculate the total working hours between login and logout times."""
        if self.login_time and self.logout_time:
            self.total_working_hours = self.logout_time - self.login_time
        else:
            self.total_working_hours = timedelta()

    def save(self, *args, **kwargs):
        # Ensure the date field is filled from login_time if it exists
        if self.login_time and not self.date:
            self.date = self.login_time.date()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.eId} - {self.login_time.date() if self.login_time else self.date}"


from django.db import models
from django.contrib.auth.models import User
from datetime import timedelta

# class Attendance(models.Model):
#     employee = models.ForeignKey(User, on_delete=models.CASCADE)
#     date = models.DateField(auto_now_add=True)
#     login_time = models.DateTimeField(null=True, blank=True)
#     logout_time = models.DateTimeField(null=True, blank=True)
#     login_location = models.CharField(max_length=255, null=True, blank=True)
#     logout_location = models.CharField(max_length=255, null=True, blank=True)
#     total_working_hours = models.DurationField(default=timedelta)
#     total_working_days = models.IntegerField(default=0)

    # def calculate_working_hours(self):
    #     """Calculate total working hours based on login and logout time."""
    #     if self.login_time and self.logout_time:
    #         return self.logout_time - self.login_time
    #     return timedelta()

    # def save(self, *args, **kwargs):
    #     self.total_working_hours = self.calculate_working_hours()
    #     super().save(*args, **kwargs)

    # def __str__(self):
    #     return f"{self.employee.username} - {self.date}"
    

class Notice(models.Model):
    employee = models.ForeignKey('Employee', on_delete=models.CASCADE,default=1)
    Id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=250)
    description = models.TextField()
    publishDate = models.DateTimeField()
    is_global = models.BooleanField(default=False)

    def __str__(self):
        return self.title 
    

class workAssignments(models.Model):
    Id = models.CharField(max_length=20)
    assignerId = models.ForeignKey(Employee,on_delete=models.CASCADE,related_name="assignerId")
    work = models.TextField()
    assignDate = models.DateTimeField()
    dueDate = models.DateTimeField()
    taskerId = models.ForeignKey(Employee,on_delete=models.CASCADE,related_name="taskerId") 
class SalaryDisbursement(models.Model):
    STATUS_CHOICES = [
        ('Paid', 'Paid'),
        ('Unpaid', 'Unpaid'),
        ('Hold', 'Hold'),
    ]

    employee = models.ForeignKey('Employee', on_delete=models.CASCADE)
    month = models.CharField(
        max_length=20,
        choices=[
            ('January', 'January'), ('February', 'February'), ('March', 'March'),
            ('April', 'April'), ('May', 'May'), ('June', 'June'),
            ('July', 'July'), ('August', 'August'), ('September', 'September'),
            ('October', 'October'), ('November', 'November'), ('December', 'December')
        ],
        default=datetime.now().strftime('%B')  # Default to current month
    )
    year = models.PositiveIntegerField(default=datetime.now().year)
    total_salary = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='Unpaid')
    salary_release_date = models.DateField(null=True, blank=True)  # For "Paid" option

    class Meta:
        unique_together = ('employee', 'month', 'year')
        ordering = ['-year', 'month', 'employee']

    def __str__(self):
        return f"{self.employee.firstName} - {self.month} {self.year} ({self.status})"

from django.db import models
class BusinessExpenditure(models.Model):
    employee = models.ForeignKey('Employee', on_delete=models.CASCADE)
    expenditure_name = models.CharField(max_length=200)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    expenditure_date = models.DateField()
    status = models.CharField(max_length=20, choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')])

    def __str__(self):
        return f"Expenditure {self.expenditure_name} by {self.employee}"

    def __str__(self):
        return f"Expenditure {self.expenditure_name} by {self.employee}"

class RequestType(models.Model):
    TYPE_CHOICES = [
        ('expenditure', 'Expenditure Request'),
        ('leave', 'Leave Request'),
        ('other', 'Other Request'),
    ]
    
    name = models.CharField(max_length=50, choices=TYPE_CHOICES)
    
    def __str__(self):
        return self.name

from django.utils.timezone import now  # Import this
class Requests(models.Model):
    EXPENDITURE = 'expenditure'
    LEAVE = 'leave'
    OTHER = 'other'
    
    REQUEST_TYPE_CHOICES = [
        (EXPENDITURE, 'Expenditure Request'),
        (LEAVE, 'Leave Request'),
        (OTHER, 'Other Request'),
    ]

    requester = models.ForeignKey('Employee', on_delete=models.CASCADE)
    request_type = models.CharField(max_length=50, choices=REQUEST_TYPE_CHOICES)
    title = models.CharField(max_length=200)
    message = models.TextField()
    date = models.DateField(auto_now_add=True)
    

    # For expenditure requests
    amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    paid_status = models.CharField(max_length=20, choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('pending', 'Pending')], null=True, blank=True)

    # For leave requests
    from_date = models.DateField(null=True, blank=True)
    to_date = models.DateField(null=True, blank=True)
    
    # Additional fields and methods as needed
    def __str__(self):
        return f"{self.request_type} request by {self.requester}"

class ExpenditureRequest(models.Model):
    STATUS_CHOICES = (
        ('Pending', 'Pending'),
        ('Approved', 'Approved'),
        ('Paid', 'Paid'),
        ('Unpaid', 'Unpaid'),
        ('Deleted', 'Deleted'),
    )

    employee = models.ForeignKey('Employee', on_delete=models.CASCADE)
    expenditure_name = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='Pending')
    created_at = models.DateTimeField(auto_now_add=True)  # Timestamp for history


    def __str__(self):
        return f"Expenditure Request {self.id} by {self.employee.firstName} {self.employee.lastName} ({self.employee.eID})"

class LeaveRequest(models.Model):
    STATUS_CHOICES = (
        ('Pending', 'Pending'),
        ('Approved', 'Approved'),
        ('Deleted', 'Deleted'),
        ('Hold', 'Hold'),
    )

    employee = models.ForeignKey('Employee', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    from_date = models.DateField()
    to_date = models.DateField()
    days = models.IntegerField(default=0)  # New field to store number of days
    message = models.TextField()

templates/employee/admin_dashboard.html
<h2>Employee Attendance Records</h2>
<table>
    <thead>
        <tr>
            <th>Employee</th>
            <th>Date</th>
            <th>Login Time</th>
            <th>Login Location</th>
            <th>Logout Time</th>
            <th>Logout Location</th>
            <th>Total Hours</th>
        </tr>
    </thead>
    <tbody>
        {% for record in records %}
            <tr>
                <td>{{ record.employee.username }}</td>
                <td>{{ record.date }}</td>
                <td>{{ record.login_time }}</td>
                <td>{{ record.login_location }}</td>
                <td>{{ record.logout_time }}</td>
                <td>{{ record.logout_location }}</td>
                <td>{{ record.total_working_hours }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

templates/employee/assign_task.html
{% extends 'base.html' %}

{% block content %}
  <h2>Assign Task to Employee</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Assign Task</button>
  </form>
{% endblock %}

templates/employee/assignedworklist.html
{% extends 'base.html' %}

{% block content %}
    <h1>Assigned Work List</h1>
    <table>
        <thead>
            <tr>
                <th>Employee</th>
                <th>Task Title</th>
                <th>Description</th>
                <th>Assigned Date</th>
                <th>Due Date</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for assignment in assignments %}
                <tr>
                    <td>{{ assignment.employee }}</td>
                    <td>{{ assignment.task_title }}</td>
                    <td>{{ assignment.description }}</td>
                    <td>{{ assignment.assigned_date }}</td>
                    <td>{{ assignment.due_date }}</td>
                    <td>{{ assignment.status }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="6">No work assignments found.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/employee/ex.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="{% static './css/style.css' %}">
    <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
    <link href='https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css' rel='stylesheet'>
    
    <title>Employee Management</title> 
</head>
<body>
    <nav class="sidebar close">
        <header>
            <div class="image-text">
                <span class="image">
                    <img src="{% static 'assets/logo.png' %}" alt="">
                </span>

                <div class="text logo-text">
                    <span class="name">Employee</span>
                    <span class="profession">Management</span>
                </div>
            </div>

            <i class='toggle'></i>
        </header>

        <div class="menu-bar">
            <div class="menu">

                <ul class="menu-links">
                    <li class="nav-link">
                        <a href="/ems/dashboard">
                            <i class='bx bx-home-alt icon' ></i>
                            <span class="text nav-text">Dashboard</span>
                        </a>
                    </li>

                    <li class="nav-link">
                        <a href="/ems/assignwork">
                            <i class='bx bx-bar-chart-alt-2 icon' ></i>
                            <span class="text nav-text">Assign Work</span>
                        </a>
                    </li>

                    <li class="nav-link">
                        <a href="/ems/notice">
                            <i class='bx bx-bell icon'></i>
                            <span class="text nav-text">Notice</span>
                        </a>
                    </li>

                    <li class="nav-link">
                        <a href="{% url 'user_notifications' %}">
                            <i class='bx bx-bell icon'></i>
                            <span class="text nav-text">Notifications</span>
                        </a>
                    </li>

                    <li class="nav-link">
                        <a href="/ems/make_request/">
                            <i class='bx bx-message-error icon' ></i>
                            <span class="text nav-text">Request</span>
                        </a>
                    </li>

                    <li class="nav-link">
                        <a href="{% url 'attendance_summary' %}">
                            <i class='bx bx-calendar icon'></i>
                            <span class="text nav-text">Attendance</span>
                        </a>
                    </li>                    

                    <li class="nav-link">
                        <a href="/ems/my_work/">
                            <i class='bx bx-task icon'></i>
                            <span class="text nav-text">My Work</span>
                        </a>
                    </li>
                    
                    <li class="nav-link">
                        <a href="/ems/editAW">
                            <i class='bx bx-edit-alt icon' ></i>
                            <span class="text nav-text">Edit Assigned Works</span>
                        </a>
                    </li>
                    
                </ul>
            </div>

             <div class="bottom-content">
                <li class="nav-link">
                    <form id="logout-form" action="{% url 'logout_user' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" id="logout_location" name="logout_location">
                        <a href="javascript:void(0);" onclick="sendLogoutLocation();">
                            <i class='bx bx-log-out icon'></i>
                            <span class="text nav-text">Logout</span>
                        </a>
                    </form>
                    
                </li>               
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}
   
    <script>
        function sendLogoutLocation() {
    // Check if Geolocation is supported
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(
            function (position) {
                const latitude = position.coords.latitude;
                const longitude = position.coords.longitude;
                const logoutLocation = `${latitude},${longitude}`;
                
                // Set the logout location in the hidden input
                document.getElementById('logout_location').value = logoutLocation;
                
                console.log("Fetched logout location:", logoutLocation);
                
                // Submit the logout form
                document.getElementById('logout-form').submit();
            },
            function (error) {
                console.error("Error fetching location:", error.message);
                alert('Unable to fetch location. Please allow location access and try again.');
            }
        );
    } else {
        alert('Geolocation is not supported by this browser.');
    }
}

    </script>
    <script src="{% static './js/script.js' %}"></script>
</body>
</html>

templates/employee/extra.html
<!-- {% extends 'base.html' %}

{% block content %}
<section class="home">
    <div class="text">Make Request</div>
    
  
    {% if messages %}
    <ul>
        {% for message in messages %}
        <li class="{{ message.tags }}">{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <div>
        <button onclick="showForm('expenditure')">Expenditure Request</button>
        <button onclick="showForm('leave')">Leave Request</button>
        <button onclick="showForm('other')">Other Request</button>
    </div>

   
   
    <form id="expenditure" method="post" action="{% url 'expenditure_requests' %}" style="display: none;">
        {% csrf_token %}
        <label for="id_Expenditure_Name">Expenditure Name: </label>
        <input type="text" name="expenditure_name" id="expenditure_name"><br>
        <label for="id_Amount">Amount: </label>
        <input type="number" name="amount" id="amount"><br>
        <label for="id_date">Date: </label>
        <input type="date" name="date" id="date"><br>
        <input type="hidden" name="form_type" value="expenditure">
        <button type="submit">Submit</button>
    </form>

    <form id="leave" method="post" style="display: none;">
        {% csrf_token %}
        {{ leave_form.as_p }}
        <input type="hidden" name="form_type" value="leave">
        <button type="submit">Submit</button>
    </form>

 
    <form id="other" method="post" style="display: none;">
        {% csrf_token %}
        {{ other_form.as_p }}
        <input type="hidden" name="form_type" value="other">
        <button type="submit">Submit</button>
    </form>
</section>

<script>
    function showForm(formType) {
        document.getElementById('expenditure').style.display = 'none';
        document.getElementById('leave').style.display = 'none';
        document.getElementById('other').style.display = 'none';
        document.getElementById(formType).style.display = 'block';
    }
</script>
{% endblock %} 


 -->

templates/employee/my__work.html
{% extends 'base.html' %}

{% block content %}
  <h2>My Tasks</h2>
  
  {% if tasks %}
    <ul>
      {% for task in tasks %}
        <li>
          <strong>{{ task.task_details }}</strong><br>
          Assigned on: {{ task.assign_date }}<br>
          Due on: {{ task.due_date }}<br>
          Status: {% if task.is_completed %} Completed {% else %} Pending {% endif %}
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No tasks assigned to you.</p>
  {% endif %}
{% endblock %}

templates/employee/submit_expenditure.html
{% extends 'base.html' %}

{% block content %}
<section class="home">
    <div class="text">
        <h2>Submit Expenditure Request</h2>
        <div class="form-container" style="max-width: 600px; margin: auto;">
            <form method="post">
                {% csrf_token %}
                <div style="margin-bottom: 10px;">
                    <label for="id_Expenditure_Name">Expenditure Name:</label><br>
                    {{ form.Expenditure_Name }}
                </div>
                <div style="margin-bottom: 10px;">
                    <label for="id_Amount">Amount:</label><br>
                    {{ form.Amount }}
                </div>
                <div style="margin-bottom: 10px;">
                    <label for="id_Date">Date:</label><br>
                    {{ form.Date }}
                </div>
                <div style="margin-top: 20px;">
                    <button type="submit" style="padding: 10px 20px; background-color: #6366f1; color: white; border: none; border-radius: 5px;">
                        Submit Request
                    </button>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}